name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build (with config)
      run: cargo build --release --features=default-config --verbose
    - name: Run tests (with config)
      run: cargo clippy --release --features=default-config --all -- -D warnings
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo clippy --release --all -- -D warnings
    - uses: actions/upload-artifact@v2
      with:
        name: rust-ddns-${{ matrix.os }}
        path: |
          target/release/rust-ddns
          target/release/rust-ddns.exe
